### NumPy

In [ ]:

'''

A. Difference between List & Array

1. Creating NumPy Arrays
    - 1D & 2D Arrays
    - np.array([])
    - np.arange()
    - np.linspace()
    - np.ones()
    - np.zeros()

2. NumPy Random
    - np.random.randint
    - np.random.randn
    - np.random.random

3. Array Operations
    - Scalar Addition / Multiplication / Division
    - Statistical & Aggregate Functions
        - Mean(), Std(), Var(), Sum()
    - Array Reshaping
    - Array Stacking (np.vstack(), np.hstack())

4. Indexing & Slicing

'''


In [1]:
import numpy as np

#### Creating an Array

In [2]:
v = [i for i in range(5)]

print(v)

[0, 1, 2, 3, 4]


In [4]:
a = np.array(v)

print(a)

[0 1 2 3 4]


In [5]:
v2 = []
for i in v:

    v2.append(i**2)

print(v2)


[0, 1, 4, 9, 16]


In [7]:
a1 = a + 2
print(a1)

[2 3 4 5 6]


In [11]:
a2 = np.arange(4, 16, dtype='float')

print(a2)

[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


#### NumPy Random

In [19]:
np.random.random(10)

array([0.37661701, 0.0450709 , 0.86221462, 0.19332339, 0.52302342,
       0.08454254, 0.30247742, 0.79658661, 0.55518277, 0.66530263])

In [44]:
np.random.rand(23)

array([0.01823207, 0.28632743, 0.82998012, 0.63164521, 0.5722667 ,
       0.12780927, 0.07829759, 0.10195385, 0.65932747, 0.79364187,
       0.80116373, 0.5994543 , 0.70348814, 0.87324446, 0.48850846,
       0.43153608, 0.59121972, 0.59363404, 0.05682837, 0.9068499 ,
       0.37233805, 0.85676608, 0.16916822])

In [50]:
np.random.randint(20, 50, size=(10))

array([20, 30, 20, 40, 38, 35, 44, 33, 36, 49])

In [51]:
np.random.randint(20, 50, size=(5,5))

array([[37, 42, 25, 29, 26],
       [31, 29, 28, 31, 33],
       [46, 36, 49, 34, 42],
       [28, 21, 41, 37, 29],
       [29, 36, 37, 31, 39]])

In [52]:
import pandas as pd


In [54]:
pd.DataFrame(np.random.randint(20, 50, size=(5,5)), columns=list('ABCDE'))

A   B   C   D   E
0  40  45  33  28  38
1  40  21  47  44  42
2  25  32  22  26  48
3  26  21  29  43  28
4  21  40  29  27  26

In [59]:
a2 = np.linspace(0, 1, 100)

In [60]:
a2.ndim

1

In [63]:
a2.reshape(10,10)

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

#### Array Operations

In [64]:
v1 = np.random.randint(20,40, size=(10, 2))

In [65]:
v1

array([[24, 27],
       [37, 35],
       [31, 21],
       [28, 34],
       [26, 32],
       [25, 36],
       [38, 30],
       [21, 25],
       [28, 21],
       [30, 36]])

In [66]:
v1[(v1 > 25)]

array([27, 37, 35, 31, 28, 34, 26, 32, 36, 38, 30, 28, 30, 36])

In [67]:
v3 = v1 + 0.25

array([[24.25, 27.25],
       [37.25, 35.25],
       [31.25, 21.25],
       [28.25, 34.25],
       [26.25, 32.25],
       [25.25, 36.25],
       [38.25, 30.25],
       [21.25, 25.25],
       [28.25, 21.25],
       [30.25, 36.25]])

In [70]:
v1.max()

38

In [78]:
np.sort(v1)

array([[24, 27],
       [35, 37],
       [21, 31],
       [28, 34],
       [26, 32],
       [25, 36],
       [30, 38],
       [21, 25],
       [21, 28],
       [30, 36]])

In [71]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.ones(30).reshape(10,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
v3 = v1 + 0.25

print(v3)

[[24.25 27.25]
 [37.25 35.25]
 [31.25 21.25]
 [28.25 34.25]
 [26.25 32.25]
 [25.25 36.25]
 [38.25 30.25]
 [21.25 25.25]
 [28.25 21.25]
 [30.25 36.25]]


In [81]:
v4 = v1 + 0.45

print(v4)

[[24.45 27.45]
 [37.45 35.45]
 [31.45 21.45]
 [28.45 34.45]
 [26.45 32.45]
 [25.45 36.45]
 [38.45 30.45]
 [21.45 25.45]
 [28.45 21.45]
 [30.45 36.45]]


In [83]:
np.vstack((v3, v4))

array([[24.25, 27.25],
       [37.25, 35.25],
       [31.25, 21.25],
       [28.25, 34.25],
       [26.25, 32.25],
       [25.25, 36.25],
       [38.25, 30.25],
       [21.25, 25.25],
       [28.25, 21.25],
       [30.25, 36.25],
       [24.45, 27.45],
       [37.45, 35.45],
       [31.45, 21.45],
       [28.45, 34.45],
       [26.45, 32.45],
       [25.45, 36.45],
       [38.45, 30.45],
       [21.45, 25.45],
       [28.45, 21.45],
       [30.45, 36.45]])

In [85]:
v5 = np.hstack((v3, v4))

In [89]:
v5[2:, 1:]

array([[21.25, 31.45, 21.45],
       [34.25, 28.45, 34.45],
       [32.25, 26.45, 32.45],
       [36.25, 25.45, 36.45],
       [30.25, 38.45, 30.45],
       [25.25, 21.45, 25.45],
       [21.25, 28.45, 21.45],
       [36.25, 30.45, 36.45]])

In [92]:
v4.std()

29.087500000000016